name: Github Actions Testing
'on':
  push:
    branches:
      - main
      - dev
env:
  DEPLOY_VER: SHA
  YEAR: 2020
jobs:
  first-job:
    runs-on: ubuntu-latest
    env:
      DEPLOY_VER: SHA
    steps:
    - name: Print the list of files/directories in github repository
      run: ls
    - name: Print content of log.txt file
      run: pwd
    - name: after cd...
      run: ./0c7e854e-3ef3-488d-b632-0f07aa3bcb2f.sh
    - name: after pwd
      run: pwd
    - name: Print Hello from env variable
      run: echo "Hello from $DEPLOY_VER"
  second-job:
    runs-on: ubuntu-latest
    env:
      MONTH: February
    steps:
    - name: Print the system date and time
      run: date
    - name: Print the variable's content
      run: echo "Day - $DAY__OF_THE_MONTH; Month - $MONTH; Year - $YEAR"
